# name: publish
# on:
#   push:
#     branches:
#       - master
# jobs:
#   custom-publish:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Set up Node
#         uses: actions/setup-node@v2
#         with:
#           node-version: '16.19.x'
#           registry-url: 'https://registry.npmjs.org'
#         env:
#           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

#       - name: Install dependencies
#         run: yarn

#       - name: Run Custom Publish
#         run: npm run custom-publish
